apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devjams-web.fullname" . }}-config
  labels:
    {{- include "devjams-web.labels" . | nindent 4 }}
data:
  SERVER_URL: {{ .Values.config.serverUrl | quote }}
  ENV: {{ .Values.config.env | quote }}
