{{- if .Values.middleware.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "devjams-deployment.fullname" . }}-default-headers
  labels:
    {{- include "devjams-deployment.labels" . | nindent 4 }}
spec:
  headers:
    {{- toYaml .Values.middleware.headers | nindent 4 }}
{{- end }}
