apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devjams-deployment.fullname" . }}-secrets
  labels:
    {{- include "devjams-deployment.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
